version: 0.2
env:
  variables:
    SANITY_PROJECT_ID: '1vz4sc35'
    SANITY_DATASET: 'production'
    ENABLE_GATSBY_REFRESH_ENDPOINT: 'true'
    TARGET_BUCKET_NAME: 'twguy.co.uk'
    TARGET_ADDRESS: 'https://twguy.co.uk'
    AWS_REGION: 'eu-west-2'
phases:
  install:
    commands:
      - 'touch .npmignore'
      - n 14.19.1
      - 'npm install -g gatsby'
  pre_build:
    commands:
      - 'cd web'
      - 'npm ci --production'
  build:
    commands:
      - 'npm run build'
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://twguy.co.uk" --delete --acl "public-read"'
artifacts:
  baseDirectory: web/public
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - '.cache/*'
    - 'public/*'
