version: 0.2

env:
  variables:
    SANITY_PROJECT_ID: '1vz4sc35'
    SANITY_DATASET: 'production'
    S3_BUCKET: 'twguy.co.uk'

phases:
  install:
    commands:
      - 'touch .npmignore'
      - n 14.19.1
      - 'npm install -g gatsby-cli'
  pre_build:
    commands:
      - 'cd web'
      - 'npm ci --production'
  build:
    commands:
      - 'npm run build'
  post_build:
    commands:
      - 'npm run deploy'
      - 'aws s3 sync "public/" "s3://${S3_BUCKET}" --delete --acl "bucket-owner-full-control"'

artifacts:
  baseDirectory: 'web/public'
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - '.cache/*'
    - 'public/*'
